### ISSUE TITLE
row click event doesn't fire from a component included in a page on Wak 10 (beta)

### ISSUE THREAD

**Issue by AMorgaut** [vegarringdal/GridView#11]
Steps to reproduce

- create a component
- add a GridView
- bind it to a datasource
- add at least one column linked to an attribute
- from the event tab, add "On row Single click" event handler with alert('click ok')
- run directly the component to test and click on a row -> the alert box pop up

- create a Page
- add the component to the page
- run the page to test and click on a row -> the alert box doesn't pop up

**Comment by vegarringdal** [comment]
I still dont see the issue, works just fine in chrome, ie11, firefix, safrari

unpack:
https://dl.dropboxusercontent.com/u/23375256/wakanda.org/gridgithubIssues/Untitled1.zip

start solution
open on page

http://127.0.0.1:8081/index.waPage/index.html?debug=1

**Comment by vegarringdal** [comment]
using 10.176700, windows 8.1, 32bit

**Comment by AMorgaut** [comment]
Here is the project with the issue:
https://onedrive.live.com/redir?resid=EFC007CDB3ED9A04!383&authkey=!AH2k6edEpGq12Y4&ithint=file%2czip

Using Wakanda Entreprise 10 build 177731
From Chrome 40.0.2214.93 (64-bit)
On Mac OS

**Comment by AMorgaut** [comment]
It works from your project/page on my system

I don't get yet the difference between the 2 projects

**Comment by vegarringdal** [comment]
The bug has been fixed properly on WAK10 from Build 178404.

I havent had time to test it yet.

**Comment by vegarringdal** [comment]
added update to grid btw, so now scrolling should be more smoother... done by filling client side cache more often.

**Comment by vegarringdal** [comment]
just did a test with 10.179294 and it works in v2 of gridview, closing issue
